spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
