spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  security:
    jwt:
      secret: supersecretjwtkeysupersecretjwtkey123
      expiration: 86400000

server:
  port: 8081