spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092